version: "3.9"

services:
  db:
    image: mariadb:11   
    container_name: timetable-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${SQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${SQL_DATABASE}'             
      MYSQL_USER:  '${SQL_USER}'
      MYSQL_PASSWORD: '${SQL_PASSWORD}'
    ports:
      - "3316:3306"   
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root -p$SQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: ./api
    container_name: timetable-api
    restart: unless-stopped
    command: ["uv", "run", "uvicorn", "main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    environment:
      SQL_ROOT_PASSWORD: '${SQL_ROOT_PASSWORD}'
      SQL_DATABASE: '${SQL_DATABASE}'             
      SQL_USER:  '${SQL_USER}'
      SQL_PASSWORD: '${SQL_PASSWORD}'
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
      - /app/.venv
    depends_on:
      db:
        condition: service_healthy
    
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile.dev 
    container_name: timetable-web
    restart: unless-stopped
    ports:
      - "5173:5173" 
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - api

