version: "3.9"

services:
  db:
    image: mariadb:11   
    container_name: timetable-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${SQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${SQL_DATABASE}'             
      MYSQL_USER:  '${SQL_USER}'
      MYSQL_PASSWORD: '${SQL_PASSWORD}'
    ports:
      - "3316:3306"   
    # volumes:
      # - db_data:/var/lib/mysql       
      # - ./initdb:/docker-entrypoint-initdb.d     
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root -p$SQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: ./api
    container_name: timetable-api
    restart: unless-stopped
    command: tail -f /dev/null
    environment:
      CONNECTION: '${CONNECTION}'
    ports:
      - "5000:5000"

  # web:
  #   build: ./web
  #   container_name: timetable-web
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"

# volumes:
  # db_data:

